In [240]:
import pandas as pd
import numpy as np
from scipy import stats

In [241]:
df = pd.read_csv(filepath_or_buffer="data_process.csv", header= None)
coloums = [ 'DateConsommation','Produit','Fournisseur','Nuance','CodeAcier','CoilId','BobineId','BobinePhysId',
           'Xpos','Absorptivite','Epaisseur','Largeur','ConsigneTemperatureLunetteCoin','CorrectionNuanceAppliquee',
           'TemperatureLunCoin','ConsigneTemperatureBainAvant','ConsigneTemperatureBainArriere','TemperatureBainAV',
           'TemperatureBainAR','TemperatureBainAlu','TendanceBain','THR','VitesseCentre']

df.columns = coloums  
df.head()

,DateConsommation,Produit,Fournisseur,Nuance,CodeAcier,CoilId,BobineId,BobinePhysId,Xpos,Absorptivite,...,CorrectionNuanceAppliquee,TemperatureLunCoin,ConsigneTemperatureBainAvant,ConsigneTemperatureBainArriere,TemperatureBainAV,TemperatureBainAR,TemperatureBainAlu,TendanceBain,THR,VitesseCentre
0,2023-05-12 11:05:14.277000,CAC,DK,MB (87778),MB,215741,7816210,781621,0.0,0.701835,...,0.0,459.846548,450.0,452.0,453.0,452.0,446.067595,0.566202,False,42.0
1,2023-05-12 11:05:14.277000,CAC,DK,MB (87778),MB,215741,7816210,781621,10.0,0.717801,...,0.0,456.106208,450.0,452.0,453.0,452.0,446.998686,0.100657,False,42.0
2,2023-05-12 11:05:14.277000,CAC,DK,MB (87778),MB,215741,7816210,781621,20.0,0.721926,...,0.0,451.485320,450.0,452.0,453.0,452.0,447.000000,0.006726,False,42.0
3,2023-05-12 11:05:14.277000,CAC,DK,MB (87778),MB,215741,7816210,781621,30.0,0.723906,...,0.0,449.324217,450.0,452.0,453.0,452.0,447.000000,-1.384546,False,41.9
4,2023-05-12 11:05:14.277000,CAC,DK,MB (87778),MB,215741,7816210,781621,40.0,0.721577,...,0.0,448.230761,450.0,452.0,453.0,452.0,447.000000,-2.555693,False,42.0

In [242]:
df

,DateConsommation,Produit,Fournisseur,Nuance,CodeAcier,CoilId,BobineId,BobinePhysId,Xpos,Absorptivite,...,CorrectionNuanceAppliquee,TemperatureLunCoin,ConsigneTemperatureBainAvant,ConsigneTemperatureBainArriere,TemperatureBainAV,TemperatureBainAR,TemperatureBainAlu,TendanceBain,THR,VitesseCentre
0,2023-05-12 11:05:14.277000,CAC,DK,MB (87778),MB,215741,7816210,781621,0.0,0.701835,...,0.0,459.846548,450.0,452.0,453.0,452.0,446.067595,0.566202,False,42.0
1,2023-05-12 11:05:14.277000,CAC,DK,MB (87778),MB,215741,7816210,781621,10.0,0.717801,...,0.0,456.106208,450.0,452.0,453.0,452.0,446.998686,0.100657,False,42.0
2,2023-05-12 11:05:14.277000,CAC,DK,MB (87778),MB,215741,7816210,781621,20.0,0.721926,...,0.0,451.485320,450.0,452.0,453.0,452.0,447.000000,0.006726,False,42.0
3,2023-05-12 11:05:14.277000,CAC,DK,MB (87778),MB,215741,7816210,781621,30.0,0.723906,...,0.0,449.324217,450.0,452.0,453.0,452.0,447.000000,-1.384546,False,41.9
4,2023-05-12 11:05:14.277000,CAC,DK,MB (87778),MB,215741,7816210,781621,40.0,0.721577,...,0.0,448.230761,450.0,452.0,453.0,452.0,447.000000,-2.555693,False,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2222924,2022-01-02 06:55:04.667000,BAF,MK,BT (88098),BT,185018,7472170,747217,460.0,0.570552,...,5.0,470.312450,454.0,454.0,450.0,450.0,442.000000,6.000000,False,49.9
2222925,2022-01-02 06:55:04.667000,BAF,MK,BT (88098),BT,185018,7472170,747217,470.0,0.572883,...,5.0,500.336929,454.0,454.0,450.0,450.0,442.000000,6.000000,False,49.9
2222926,2022-01-02 06:55:04.667000,BAF,MK,BT (88098),BT,185018,7472170,747217,480.0,0.575152,...,5.0,510.953755,454.0,454.0,450.0,450.0,442.000000,6.000000,False,49.9
2222927,2022-01-02 06:55:04.667000,BAF,MK,BT (88098),BT,185018,7472170,747217,490.0,0.572661,...,5.0,491.466765,454.0,454.0,450.0,450.0,442.000000,6.000000,False,49.9
2222928,2022-01-02 06:55:04.667000,BAF,MK,BT (88098),BT,185018,7472170,747217,500.0,0.574654,...,5.0,463.309979,454.0,454.0,450.0,450.0,442.000000,6.000000,False,49.9

In [243]:
df = df.dropna()

In [244]:
df['DateConsommation'] = pd.to_datetime(df['DateConsommation'])

C:\Users\elmehdi.berchid\AppData\Local\Temp\ipykernel_19980\4177593574.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DateConsommation'] = pd.to_datetime(df['DateConsommation'])

In [245]:
import re
def extract_numbers(nuance):
    numbers = re.findall(r'\((\d+)\)', nuance)
    if numbers:
        return numbers[0][1:-1] 
    else:
        return None

In [246]:
df['new_col'] = df['Nuance'].apply(extract_numbers)
df['Nuance'] = df['new_col']
df = df.drop(columns=['new_col'])
df.head(10)

C:\Users\elmehdi.berchid\AppData\Local\Temp\ipykernel_19980\1026398326.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['new_col'] = df['Nuance'].apply(extract_numbers)
C:\Users\elmehdi.berchid\AppData\Local\Temp\ipykernel_19980\1026398326.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Nuance'] = df['new_col']

,DateConsommation,Produit,Fournisseur,Nuance,CodeAcier,CoilId,BobineId,BobinePhysId,Xpos,Absorptivite,...,CorrectionNuanceAppliquee,TemperatureLunCoin,ConsigneTemperatureBainAvant,ConsigneTemperatureBainArriere,TemperatureBainAV,TemperatureBainAR,TemperatureBainAlu,TendanceBain,THR,VitesseCentre
0,2023-05-12 11:05:14.277,CAC,DK,777,MB,215741,7816210,781621,0.0,0.701835,...,0.0,459.846548,450.0,452.0,453.0,452.0,446.067595,0.566202,False,42.000000
1,2023-05-12 11:05:14.277,CAC,DK,777,MB,215741,7816210,781621,10.0,0.717801,...,0.0,456.106208,450.0,452.0,453.0,452.0,446.998686,0.100657,False,42.000000
2,2023-05-12 11:05:14.277,CAC,DK,777,MB,215741,7816210,781621,20.0,0.721926,...,0.0,451.485320,450.0,452.0,453.0,452.0,447.000000,0.006726,False,42.000000
3,2023-05-12 11:05:14.277,CAC,DK,777,MB,215741,7816210,781621,30.0,0.723906,...,0.0,449.324217,450.0,452.0,453.0,452.0,447.000000,-1.384546,False,41.900000
4,2023-05-12 11:05:14.277,CAC,DK,777,MB,215741,7816210,781621,40.0,0.721577,...,0.0,448.230761,450.0,452.0,453.0,452.0,447.000000,-2.555693,False,42.000000
5,2023-05-12 11:05:14.277,CAC,DK,777,MB,215741,7816210,781621,50.0,0.716567,...,0.0,447.298932,450.0,452.0,453.0,452.0,447.000000,-2.945734,False,42.000000
6,2023-05-12 11:05:14.277,CAC,DK,777,MB,215741,7816210,781621,60.0,0.715848,...,0.0,447.632109,450.0,452.0,453.0,452.0,447.000000,-2.735987,False,41.997883
7,2023-05-12 11:05:14.277,CAC,DK,777,MB,215741,7816210,781621,70.0,0.713887,...,0.0,449.688475,450.0,452.0,453.0,452.0,447.000000,-2.125313,False,42.000000
8,2023-05-12 11:05:14.277,CAC,DK,777,MB,215741,7816210,781621,80.0,0.711885,...,0.0,451.493713,450.0,452.0,453.0,452.0,447.000000,-0.962085,False,42.000000
9,2023-05-12 11:05:14.277,CAC,DK,777,MB,215741,7816210,781621,90.0,0.714152,...,0.0,451.151590,450.0,452.0,453.0,452.0,447.000000,0.027688,False,42.000000

In [247]:
df_subset = df[(df['Produit'] == 'CAC') & (df['Fournisseur'] == 'DK')]
df_subset['DiffTempAV'] = df_subset['ConsigneTemperatureBainAvant'] - df_subset['TemperatureBainAV']
df_subset['DiffTempAR'] = df_subset['ConsigneTemperatureBainArriere'] - df_subset['TemperatureBainAR']

C:\Users\elmehdi.berchid\AppData\Local\Temp\ipykernel_19980\3557123026.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['DiffTempAV'] = df_subset['ConsigneTemperatureBainAvant'] - df_subset['TemperatureBainAV']
C:\Users\elmehdi.berchid\AppData\Local\Temp\ipykernel_19980\3557123026.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['DiffTempAR'] = df_subset['ConsigneTemperatureBainArriere'] - df_subset['TemperatureBainAR']

In [248]:
df_subset[['DiffTempAR','Xpos']].describe()

         DiffTempAR          Xpos
count  1.955828e+06  1.955828e+06
mean  -3.173687e-01  3.884547e+02
std    1.398359e+00  2.786164e+02
min   -2.100000e+01  0.000000e+00
25%   -1.000000e+00  1.600000e+02
50%    0.000000e+00  3.400000e+02
75%    1.249830e-01  5.600000e+02
max    2.000000e+01  1.510000e+03

In [249]:
top_20_CodeAcier_AVfilt = df_subset['CodeAcier'].value_counts().head(20)
print(top_20_CodeAcier_AVfilt)

MB    811225
TB    289206
HE    159995
SK    132830
SD    131811
PX    129453
GR     89675
CH     49015
MC     44463
BO     32703
HT     31158
HX     16693
MX     10825
TP     10018
IF      8840
RB      7918
Name: CodeAcier, dtype: int64

In [250]:
len(df_subset)

1955828

In [251]:
Process_Nuance = pd.read_csv(filepath_or_buffer="process_nuance.csv", header= None)
head = ['CodeAcier','Nuance','CorrectionNuance']
Process_Nuance.columns = head
Process_Nuance.columns

Index(['CodeAcier', 'Nuance', 'CorrectionNuance'], dtype='object')

In [252]:
Process_Nuance['Nuance'] = Process_Nuance['Nuance'].astype(str)
Process_Nuance.dtypes

CodeAcier            object
Nuance               object
CorrectionNuance    float64
dtype: object

In [253]:

# First, we perform a merge operation
merged_df = pd.merge(df_subset, Process_Nuance, how='left', on=['CodeAcier', 'Nuance'])

# Then, we filter the rows where 'CorrectionNuanceAppliquee' equals 'CorrectionNuance'
filtered_df_2 = merged_df[merged_df['CorrectionNuanceAppliquee'] == merged_df['CorrectionNuance']]

In [254]:

subset_pairs = set(df_subset[['CodeAcier', 'Nuance']].itertuples(index=False))
filtered_pairs = set(filtered_df_2[['CodeAcier', 'Nuance']].itertuples(index=False))


deleted_pairs = subset_pairs - filtered_pairs

deleted_combinations = pd.DataFrame(deleted_pairs, columns=['CodeAcier', 'Nuance'])


print(deleted_combinations)

  CodeAcier Nuance
0        MB    047
1        MX    045
2        IF    032
3        HE    241
4        CH    048
5        RB    010
6        HE    326
7        MB    041
8        MC    047
9        GR    013

In [255]:
df_subset['CodeAcier_Nuance'] = df_subset['CodeAcier'].astype(str) + "_" + df_subset['Nuance'].astype(str)
deleted_combinations['CodeAcier_Nuance'] = deleted_combinations['CodeAcier'].astype(str) + "_" + deleted_combinations['Nuance'].astype(str)

deleted_counts = df_subset[df_subset['CodeAcier_Nuance'].isin(deleted_combinations['CodeAcier_Nuance'])].groupby(['CodeAcier', 'Nuance']).agg(Bobine_count = ('BobinePhysId','nunique')).reset_index()
print(deleted_counts)

C:\Users\elmehdi.berchid\AppData\Local\Temp\ipykernel_19980\2513250025.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_subset['CodeAcier_Nuance'] = df_subset['CodeAcier'].astype(str) + "_" + df_subset['Nuance'].astype(str)

  CodeAcier Nuance  Bobine_count
0        CH    048           212
1        GR    013            19
2        HE    241             2
3        HE    326             1
4        IF    032             2
5        MB    041           281
6        MB    047           287
7        MC    047             8
8        MX    045            23
9        RB    010            11

In [256]:
df_subset.columns

Index(['DateConsommation', 'Produit', 'Fournisseur', 'Nuance', 'CodeAcier',
       'CoilId', 'BobineId', 'BobinePhysId', 'Xpos', 'Absorptivite',
       'Epaisseur', 'Largeur', 'ConsigneTemperatureLunetteCoin',
       'CorrectionNuanceAppliquee', 'TemperatureLunCoin',
       'ConsigneTemperatureBainAvant', 'ConsigneTemperatureBainArriere',
       'TemperatureBainAV', 'TemperatureBainAR', 'TemperatureBainAlu',
       'TendanceBain', 'THR', 'VitesseCentre', 'DiffTempAV', 'DiffTempAR',
       'CodeAcier_Nuance'],
      dtype='object')

In [257]:
deleted_correction_means = df_subset[df_subset['CodeAcier_Nuance'].isin(deleted_combinations['CodeAcier_Nuance'])].groupby(['CodeAcier', 'Nuance']).agg(CorrectionNuance_mean = ('CorrectionNuanceAppliquee','mean')).reset_index()
print(deleted_correction_means)

  CodeAcier Nuance  CorrectionNuance_mean
0        CH    048               4.425829
1        GR    013               4.282545
2        HE    241             -10.000000
3        HE    326              -2.000000
4        IF    032               4.031851
5        MB    041               4.245335
6        MB    047              -0.266046
7        MC    047               2.909569
8        MX    045               3.916862
9        RB    010               3.900002

In [258]:
final_df = pd.merge(deleted_counts, deleted_correction_means, on=['CodeAcier', 'Nuance'])
print(final_df)

  CodeAcier Nuance  Bobine_count  CorrectionNuance_mean
0        CH    048           212               4.425829
1        GR    013            19               4.282545
2        HE    241             2             -10.000000
3        HE    326             1              -2.000000
4        IF    032             2               4.031851
5        MB    041           281               4.245335
6        MB    047           287              -0.266046
7        MC    047             8               2.909569
8        MX    045            23               3.916862
9        RB    010            11               3.900002

In [261]:
Process_Nuance[(Process_Nuance['CodeAcier'] == 'gr') & (Process_Nuance['Nuance'] == '241')]

   CodeAcier Nuance  CorrectionNuance
11        HE    241              10.0

In [239]:
df_subset = filtered_df_2

In [193]:
df_subset.shape

(1792404, 26)

In [199]:
df_subset.columns

Index(['DateConsommation', 'Produit', 'Fournisseur', 'Nuance', 'CodeAcier',
       'CoilId', 'BobineId', 'BobinePhysId', 'Xpos', 'Absorptivite',
       'Epaisseur', 'Largeur', 'ConsigneTemperatureLunetteCoin',
       'CorrectionNuanceAppliquee', 'TemperatureLunCoin',
       'ConsigneTemperatureBainAvant', 'ConsigneTemperatureBainArriere',
       'TemperatureBainAV', 'TemperatureBainAR', 'TemperatureBainAlu',
       'TendanceBain', 'THR', 'VitesseCentre', 'DiffTempAV', 'DiffTempAR',
       'CorrectionNuance'],
      dtype='object')

In [ ]:
bobine = [('TP','785'),('')]

In [194]:
# Start by creating a copy of your original dataframe before applying the filter
original_df = df_subset.copy()

# Apply your filter
bobine_ids_to_drop = df_subset.loc[(abs(df_subset['DiffTempAR']) >= 1.5 )& (df_subset['Xpos'] < 30) , 'BobineId'].unique()
df_subset = df_subset[~df_subset['BobineId'].isin(bobine_ids_to_drop)]

# Create sets of tuples representing 'CodeAcier' and 'Nuance' pairs in each dataframe
original_pairs = set(original_df[['CodeAcier', 'Nuance']].itertuples(index=False))
filtered_pairs = set(df_subset[['CodeAcier', 'Nuance']].itertuples(index=False))

# Subtract sets to get tuples that were deleted by the filter
deleted_pairs = original_pairs - filtered_pairs

# Convert tuples back to dataframe
deleted_combinations = pd.DataFrame(deleted_pairs, columns=['CodeAcier', 'Nuance'])

# Print the deleted combinations
print(deleted_combinations)

  CodeAcier Nuance
0        TP    785
1        TP    782
2        TB    316
3        HE    238
4        HT    138
5        HE    247
6        TP    772

In [ ]:
# Convert 'CodeAcier' and 'Nuance' columns to the same type (str)
original_df['CodeAcier'] = original_df['CodeAcier'].astype(str)
original_df['Nuance'] = original_df['Nuance'].astype(str)
Process_Nuance['CodeAcier'] = Process_Nuance['CodeAcier'].astype(str)
Process_Nuance['Nuance'] = Process_Nuance['Nuance'].astype(str)

# Merge 'original_df' with 'Process_Nuance' to get 'CorrectionNuance' in 'original_df'
original_df = pd.merge(original_df, Process_Nuance[['CodeAcier','Nuance','CorrectionNuance']], on=['CodeAcier','Nuance'], how='left')

# Filter 'original_df' to only include rows that have a 'CodeAcier' and 'Nuance' pair in 'deleted_combinations'
filtered_original_df = original_df[original_df[['CodeAcier', 'Nuance']].apply(tuple, axis=1).isin(deleted_combinations.apply(tuple, axis=1))]

# Group 'filtered_original_df' by 'CodeAcier' and 'Nuance', then calculate the count of 'BobineId' and the mean of 'CorrectionNuance'
final_df = filtered_original_df.groupby(['CodeAcier', 'Nuance']).agg({'BobineId': 'count', 'CorrectionNuance': 'mean'}).reset_index()

final_df.rename(columns={'BobineId': 'Count', 'CorrectionNuance': 'MeanCorrectionNuance'}, inplace=True)

print(final_df)

In [ ]:
#filtre data where Xpos < 30 and Diff bain AR < 10 
# BobineId verifie condition
bobine_ids_to_drop = df_subset.loc[(abs(df_subset['DiffTempAR']) >= 1.5 )& (df_subset['Xpos'] < 30) , 'BobineId'].unique()

#Drop all 'BobineId' 
df_subset = df_subset[~df_subset['BobineId'].isin(bobine_ids_to_drop)]

len(df_subset)

In [171]:
df_subset.columns

Index(['DateConsommation', 'Produit', 'Fournisseur', 'Nuance', 'CodeAcier',
       'CoilId', 'BobineId', 'BobinePhysId', 'Xpos', 'Absorptivite',
       'Epaisseur', 'Largeur', 'ConsigneTemperatureLunetteCoin',
       'CorrectionNuanceAppliquee', 'TemperatureLunCoin',
       'ConsigneTemperatureBainAvant', 'ConsigneTemperatureBainArriere',
       'TemperatureBainAV', 'TemperatureBainAR', 'TemperatureBainAlu',
       'TendanceBain', 'THR', 'VitesseCentre', 'DiffTempAV', 'DiffTempAR',
       'CorrectionNuance'],
      dtype='object')

In [195]:
# Start by creating a copy of your original dataframe before applying the filter
original_df = df_subset.copy()

# Apply your filter
std_devs = df_subset.groupby('BobineId')['ConsigneTemperatureBainArriere'].std()
ids_to_drop = std_devs[std_devs > 0].index
df_subset = df_subset[~df_subset['BobineId'].isin(ids_to_drop)]

# Create sets of tuples representing 'CodeAcier' and 'Nuance' pairs in each dataframe
original_pairs = set(original_df[['CodeAcier', 'Nuance']].itertuples(index=False))
filtered_pairs = set(df_subset[['CodeAcier', 'Nuance']].itertuples(index=False))

# Subtract sets to get tuples that were deleted by the filter
deleted_pairs = original_pairs - filtered_pairs

# Convert tuples back to dataframe
deleted_combinations = pd.DataFrame(deleted_pairs, columns=['CodeAcier', 'Nuance'])

# Print the deleted combinations
print(deleted_combinations)

  CodeAcier Nuance
0        HE    119
1        HX    118

In [172]:

std_devs = df_subset.groupby('BobineId')['ConsigneTemperatureBainArriere'].std()


ids_to_drop = std_devs[std_devs > 0].index


df_filtered_3= df_subset[~df_subset['BobineId'].isin(ids_to_drop)]
df_subset = df_filtered_3

In [173]:
df_subset[['BobinePhysId','Xpos','ConsigneTemperatureBainArriere','TemperatureBainAR']]

,BobinePhysId,Xpos,ConsigneTemperatureBainArriere,TemperatureBainAR
0,781621,0.0,452.0,452.0
1,781621,10.0,452.0,452.0
2,781621,20.0,452.0,452.0
3,781621,30.0,452.0,452.0
4,781621,40.0,452.0,452.0
...,...,...,...,...
2008017,747238,200.0,452.0,450.0
2008018,747238,210.0,452.0,450.0
2008019,747238,220.0,452.0,450.0
2008020,747238,230.0,452.0,450.0
2008021,747238,240.0,452.0,450.0

In [ ]:
print(df_subset['DiffTempAV'].describe())
print(df_subset['DiffTempAR'].describe())

In [196]:
top_20_CodeAcier_apresfilt = df_subset['CodeAcier'].value_counts().head(20)
top_20_CodeAcier_list = top_20_CodeAcier_apresfilt.index.tolist()

print(top_20_CodeAcier_list)

['MB', 'TB', 'HE', 'SK', 'PX', 'SD', 'GR', 'MC', 'CH', 'HT', 'BO', 'TP', 'HX', 'MX', 'IF', 'RB']

In [197]:
filtered_df = df_subset[df_subset['CodeAcier'].isin(top_20_CodeAcier_list)]
nuance_counts = filtered_df.groupby(['CodeAcier', 'Nuance']).size().reset_index(name='count')

In [198]:
# Start by creating a copy of your original dataframe before applying the filter
original_df = df_subset.copy()

# Apply your filter
nuance_counts = df_subset['Nuance'].value_counts().reset_index().rename(columns={'index': 'Nuance', 'Nuance': 'count'})
mask = nuance_counts['count'] < 100
df_subset = df_subset[~df_subset['Nuance'].isin(nuance_counts.loc[mask, 'Nuance'])]

# Create sets of tuples representing 'CodeAcier' and 'Nuance' pairs in each dataframe
original_pairs = set(original_df[['CodeAcier', 'Nuance']].itertuples(index=False))
filtered_pairs = set(df_subset[['CodeAcier', 'Nuance']].itertuples(index=False))

# Subtract sets to get tuples that were deleted by the filter
deleted_pairs = original_pairs - filtered_pairs

# Convert tuples back to dataframe
deleted_combinations = pd.DataFrame(deleted_pairs, columns=['CodeAcier', 'Nuance'])

# Print the deleted combinations
print(deleted_combinations)

  CodeAcier Nuance
0        HT    229
1        TB    224

In [ ]:
#mask on 'Nuance' 
mask = nuance_counts['count'] < 100

# Drop the rows with 'Nuance' values satisfying the mask
filtered_df = filtered_df[~filtered_df['Nuance'].isin(nuance_counts.loc[mask, 'Nuance'])]
filtered_df.head()

In [ ]:
print(filtered_df['VitesseCentre'].unique())
#[filtered_df['VitesseCentre']==40]
test = filtered_df

In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

for code_acier in top_20_CodeAcier_list:
    subset = test[test['CodeAcier'] == code_acier]
    
    for nuance in subset['Nuance'].unique():
        nuance_subset = subset[subset['Nuance'] == nuance]
        #histogram
        sns.histplot(data=nuance_subset, x='DiffTempAR', kde=True)
        
        # compute the mean or mode of CorrectionNuanceAppliquee
        mean_correction_nuance = nuance_subset['CorrectionNuanceAppliquee'].mean()
        
        # add text to the plot
        plt.text(0.5, 0.8, 'Correction de Nuance AppliquÃ©e: {:.2f}'.format(mean_correction_nuance), 
                 horizontalalignment='center', verticalalignment='center', transform=plt.gca().transAxes)
        
        plt.title(f'Distribution de TemperatureBainAR pour la Nuance: {nuance}, CodeAcier: {code_acier}')
        plt.show()

In [ ]:
def plot_correction_threshold(test, top_20_CodeAcier_list, correction_threshold):
    """
    Function to plot DiffTempAR for different nuances and CodeAcier, but only for absolute CorrectionNuanceAppliquee
    greater than or equal to a given threshold.
    """
    import numpy as np
    import seaborn as sns
    import matplotlib.pyplot as plt

    for code_acier in top_20_CodeAcier_list:
        subset = test[test['CodeAcier'] == code_acier]
        
        for nuance in subset['Nuance'].unique():
            nuance_subset = subset[(subset['Nuance'] == nuance) & 
                                   (subset['CorrectionNuanceAppliquee'].abs() >= correction_threshold)]
            if not nuance_subset.empty:  # plot only if the subset is not empty
                # histogram
                sns.histplot(data=nuance_subset, x='DiffTempAR', kde=True)
                
                # compute the mean of 'DiffTempAR'
                mean_diff_temp_ar = nuance_subset['DiffTempAR'].mean()

                # plot a vertical line for mean of 'DiffTempAR'
                plt.axvline(mean_diff_temp_ar, color='r', linestyle='--')

                # add text annotation for the mean of 'DiffTempAR'
                plt.text(mean_diff_temp_ar+0.02, 0.5, f'Mean: {mean_diff_temp_ar:.2f}', 
                         color='red', transform=plt.gca().get_xaxis_transform())
                
                # compute the mean or mode of CorrectionNuanceAppliquee
                mean_correction_nuance = nuance_subset['CorrectionNuanceAppliquee'].mean()
                
                # add text to the plot
                plt.text(0.3, 0.8, 'Correction de Nuance AppliquÃ©e: {:.2f}'.format(mean_correction_nuance), 
                         horizontalalignment='center', verticalalignment='center', transform=plt.gca().transAxes)
                
                plt.title(f'Distribution de TemperatureBainAR pour la Nuance: {nuance}, CodeAcier: {code_acier}')
                plt.show()

In [ ]:
test.head()

In [ ]:
plot_correction_threshold(test, top_20_CodeAcier_list, correction_threshold=6)

In [ ]:
filtered_df.columns

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

code_acier = 'MB'

subset = filtered_df[filtered_df['CodeAcier'] == code_acier]

for nuance in subset['Nuance'].unique():
    nuance_subset = subset[subset['Nuance'] == nuance]
    
    fig, ax1 = plt.subplots()
    
    # Create a twin y-axis for temperatureBainAr
    ax2 = ax1.twinx()
    
    # Plot temperatureBainAr as a line plot
    sns.lineplot(data=nuance_subset, x='VitesseCentre', y='DiffTempAR', color='red', ax=ax2)
    ax2.set_ylabel('DiffTempAR', color='red')
    ax2.tick_params(axis='y', labelcolor='red')
    
    plt.title(f'Distribution of Correction de Nuance for Nuance: {nuance}, CodeAcier: {code_acier}')
    plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.scatter(filtered_df['CorrectionNuance'], filtered_df['CorrectionNuanceAppliquee'])
plt.title('CorrectionNuanceAppliquee vs CorrectionNuance')
plt.xlabel('CorrectionNuance')
plt.ylabel('CorrectionNuanceAppliquee')
plt.show()

In [ ]:
test.columns

In [ ]:
test.head()

In [ ]:
codeAcier_list = top_20_CodeAcier_apresfilt.index.tolist()